version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/deploy.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 180
      runas: root
