jobs:
  - job: GetPublicIngressCert
    displayName: Get Public Ingress Cert
    steps:
      - task: Kubernetes@1
        displayName: kubectl delete TLS Cert secret
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: ${{ parameters.serviceEndpointName }}
          namespace: basic-public-ic
          command: delete
          arguments: secret default-public-tls 

      - task: DownloadSecureFile@1
        name: caCertificate
        displayName: 'Download CA certificate'
        inputs:
          secureFile: 'star_aks_dow_com.pem'      

      - task: DownloadSecureFile@1
        name: privateKey
        displayName: 'Download private Key'
        inputs:
          secureFile: 'public.key'

      - task: Kubernetes@1
        displayName: kubectl update TLS Cert secret
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: ${{ parameters.serviceEndpointName }}
          namespace: basic-public-ic
          command: create
          arguments: secret tls default-public-tls --key $(privateKey.secureFilePath) --cert $(caCertificate.secureFilePath)
 