schedules:
- cron: "30 6 * * 0"
  displayName: 'Run every week'
  branches:
    include: 
    - main
  always: true

trigger:
  - none

parameters:
  - name: sb001
    displayName: sb001
    type: boolean
    default: false
  
  - name: np002
    displayName: np002
    type: boolean
    default: true
  
  - name: pd002
    displayName: pd002
    type: boolean
    default: true

variables:
- group: AKS-vargroup

pool:
  name: WindowsDevOps
  
stages: 
  - ${{ if eq(parameters.sb001, true) }}:
    - stage: ${{ format('Back_Up_Quota_{0}', 'sb001') }}
      variables: 
        - template: ${{ format('../vars/var-{0}.yml', 'sb001') }}
      jobs:
        - job: BackUpQuota
          displayName: Backup Quota
          steps:
          - task: Kubernetes@1
            displayName: Get Quota
            name: GetQuota
            inputs:
              connectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: ${{ variables.backupEndpointName }}
              command: get
              arguments: resourcequota -A
              outputFormat: jsonpath='{range .items[*]}{.metadata.name}{" "}{.metadata.namespace}{"\n"}{end}'

          - task: PowerShell@2
            displayName: 'Wirte Result to Yaml'
            name: WritQuotaYaml
            inputs:
              targetType: 'inline'
              script: |
                $a11=$(GetQuota.KubectlOutput)
                write-output $a11 | out-file -filepath $(System.DefaultWorkingDirectory)/Clustermanagement/quota_backup.yaml -Force
                
          - publish: $(System.DefaultWorkingDirectory)/Clustermanagement/quota_backup.yaml
            artifact: ${{ format('quotaArtifact_{0}', 'sb001') }}

  - ${{ if eq(parameters.np002, true) }}:
    - stage: ${{ format('Back_Up_Quota_{0}', 'np002') }}
      variables: 
        - template: ${{ format('../vars/var-{0}.yml', 'np002') }}
      jobs:
        - job: BackUpQuota
          displayName: Backup Quota
          steps:
          - task: Kubernetes@1
            displayName: Get Quota
            name: GetQuota
            inputs:
              connectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: ${{ variables.backupEndpointName }}
              command: get
              arguments: resourcequota -A
              outputFormat: jsonpath='{range .items[*]}{.metadata.name}{" "}{.metadata.namespace}{"\n"}{end}'

          - task: PowerShell@2
            displayName: 'Wirte Result to Yaml'
            name: WritQuotaYaml
            inputs:
              targetType: 'inline'
              script: |
                $a11=$(GetQuota.KubectlOutput)
                write-output $a11 | out-file -filepath $(System.DefaultWorkingDirectory)/Clustermanagement/quota_backup.yaml -Force
                
          - publish: $(System.DefaultWorkingDirectory)/Clustermanagement/quota_backup.yaml
            artifact: ${{ format('quotaArtifact_{0}', 'np002') }}

  - ${{ if eq(parameters.pd002, true) }}:
    - stage: ${{ format('Back_Up_Quota_{0}', 'pd002') }}
      variables: 
        - template: ${{ format('../vars/var-{0}.yml', 'pd002') }}
      jobs:
        - job: BackUpQuota
          displayName: Backup Quota
          steps:
          - task: Kubernetes@1
            displayName: Get Quota
            name: GetQuota
            inputs:
              connectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: ${{ variables.backupEndpointName }}
              command: get
              arguments: resourcequota -A
              outputFormat: jsonpath='{range .items[*]}{.metadata.name}{" "}{.metadata.namespace}{"\n"}{end}'

          - task: PowerShell@2
            displayName: 'Wirte Result to Yaml'
            name: WritQuotaYaml
            inputs:
              targetType: 'inline'
              script: |
                $a11=$(GetQuota.KubectlOutput)
                write-output $a11 | out-file -filepath $(System.DefaultWorkingDirectory)/Clustermanagement/quota_backup.yaml -Force
                
          - publish: $(System.DefaultWorkingDirectory)/Clustermanagement/quota_backup.yaml
            artifact: ${{ format('quotaArtifact_{0}', 'pd002') }}