# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  paths:
    include:
    # - /your-service-name/*
  branches:
    include:
    - dev

variables:
  - template: vars/var-common.yml

stages:
  - stage: Build
    jobs:
      - template: steps/build/build.yml
        parameters:
          buildConfiguration: 'debug'

          
  - stage: Deploy
    variables:
      - template: vars/var-dev.yml
    jobs:
        parameters:
          jobEnv: ${{ variables.jobEnv }}
          serviceEndpointName: ${{ variables.serviceEndpointName }}
          keyVaultName: ${{ variables.keyVaultName }}