# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  paths:
    include:
    - /svc-envreporting-api/*
  branches:
    include:
    - dev

variables:
  - template: vars/var-common.yml

stages:
  - stage: Build
    jobs:
      - template: steps/build/build.yml
        parameters:
          buildConfiguration: 'debug'

      - template: steps/build/scan-sonarqube.yml
          
  - stage: Deploy
    variables:
      - template: vars/var-dev.yml
    jobs:
      - template: steps/build/scan-checkmarx.yml
      - template: steps/deploy-solution/deploy.yml
        parameters:
          jobEnv: ${{ variables.jobEnv }}
          serviceEndpointName: ${{ variables.serviceEndpointName }}
          password: '$(ServerPassword)'
          username: '$(Username)'