# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

variables:
  - template: vars/var-common.yml

stages:
  - stage: Build
    jobs:
      - template: steps/build/scan-sonarqube.yml
