{
 "title": "ESS-Dev (Pods)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "Status",
    "query": {
     "query": "label_values(kube_pod_status_phase,phase)"
    }
   },
   {
    "name": "ingress",
    "label": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\"},ingress)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "controller_class",
    "label": "controller_class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash,controller_class)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod, namespace, phase) (kube_pod_status_phase{namespace=~\"$namespace\",phase=~\"$Status\"}) == 1"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\"} * on (pod) ((kube_pod_status_phase{namespace=~\"$namespace\",phase=~\"$Status\"}) ==1)"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_status_phase{namespace=~\"$namespace\",phase=~\"$Status\"}) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CronJobs",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (job_name) (kube_job_status_succeeded{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\"})/ sum(kube_resourcequota{namespace=~\"$namespace\",resource=\"limits.cpu\",type=\"hard\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"$namespace\"})  / sum(kube_resourcequota{namespace=~\"$namespace\",resource=\"limits.memory\",type=\"hard\"}) *100"
    }
   ]
  },
  {
   "title": "PV Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})- sum(kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}))/ sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pods Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{namespace=~\"$namespace\",phase=~\"Running|Succeeded\"}) / (sum (kube_pod_info{namespace=~\"$namespace\"})) *100"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubeEvents \r\n| where Namespace in ($namespace)\r\n| project TimeGenerated, Name, Namespace, Reason, Message, KubeEventType",
      "resources": [
       "/subscriptions/6060ea50-d00d-4c40-8219-546ed259f9e5/resourceGroups/RG-NP-0001581"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": { "query": "" },
     "subscriptions": [
      "6060ea50-d00d-4c40-8219-546ed259f9e5"
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Success (2m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status!~\"^[4-5].*\", controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval])) / \r\n(sum(rate(nginx_ingress_controller_requests{ controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval])) - \r\n(sum(rate(nginx_ingress_controller_requests{status=~\"404|499\", controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval]))))"
    }
   ]
  },
  {
   "title": "Requests (2m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (2m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"^(1|2).*\",  controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 3xx (2m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"^3.*\",  controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "HTTP 4xx (2m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"^4.*\",  controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP 5xx (2m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"^5.*\", controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ controller_class=~\"$controller_class\", ingress=~\"$ingress\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!=\"\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!=\"\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=~\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_resourcequota{namespace=~\"$namespace\", type=\"hard\",resource=\"limits.cpu\"}) by (resourcequota)",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=~\"$namespace\"}) by (pod) "
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=~\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_resourcequota{namespace=~\"$namespace\", type=\"hard\",resource=\"limits.memory\"}) by (resourcequota)"
    }
   ]
  },
  {
   "title": "PV&PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PV&PVC Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (persistentvolumeclaim) *100"
    }
   ]
  },
  {
   "title": "PV Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (persistentvolumeclaim) /sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    }
   ]
  },
  {
   "title": "Rate of Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}