parameters:
  jobEnv: ''
  serviceEndpointName: ''
  sqlServiceEndpointName: ''
  password: ""


jobs:
  - deployment: DeploySolution
    displayName: DeploySolution
    pool:
      name: 'WindowsDevOps'
    environment: ${{ parameters.jobEnv }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: '$(serviceName)'
                downloadPath: '$(System.DefaultWorkingDirectory)'
            
            - task: WindowsMachineFileCopy@2
              displayName: 'Copy files from $(System.DefaultWorkingDirectory)/$(serviceName)/apiPkg.zip'
              inputs:
                SourcePath: '$(System.DefaultWorkingDirectory)/$(serviceName)/apiPkg.zip'
                MachineNames: '$(WebServers)'
                AdminUserName: '${{ parameters.username }}'
                AdminPassword: '${{ parameters.password }}'
                TargetPath: 'E:\Replace\yourpath\here'
          
            - task: PowerShell@2
              displayName: 'Deploy the $(resourceName)'
              inputs:
                targetType: 'filePath'
                pwsh: true
                filePath: $(System.DefaultWorkingDirectory)/$(serviceName)/scripts/deploywebsitestoIaaS.ps1
                arguments:
                  -User '${{ parameters.username }}'
                  -pass '${{ parameters.password }}'
                  -Computer '$(WebServers)'
                  -resourceName '$(resourceName)'
                  -env '$(env)'
                  -backupPath 'E:\Replace\yourpath\here\apibackup.zip'
                  -updatePackagePath 'E:\Replace\yourpath\here\apiPkg.zip'
                  -appPath 'E:\Replace\yourpath\here\api'

                
                  