{
 "title": "Cluster-Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\"},cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash, controller_class) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1- sum(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\",node=~\"$node\"})/sum(node_cpu_seconds_total{cluster=\"$cluster\",node=~\"$node\"}))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-sum(node_memory_MemAvailable_bytes{cluster=\"$cluster\",node=~\"$node\"})/sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",node=~\"$node\"}))*100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-sum(node_filesystem_avail_bytes{cluster=\"$cluster\",node=~\"$node\",mountpoint=\"/\"})/sum(node_filesystem_size_bytes{cluster=\"$cluster\",node=~\"$node\",mountpoint=\"/\"}))*100"
    }
   ]
  },
  {
   "title": "Pods Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kubelet_running_pods{cluster=\"$cluster\",node=~\"$node\"}) / (sum (kube_pod_info{cluster=\"$cluster\",node=~\"$node\",pod!~\".*deployment-restart.*\"})) *100"
    }
   ]
  },
  {
   "title": "Cluster CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1- sum(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\",node=~\"$node\"})/sum(node_cpu_seconds_total{cluster=\"$cluster\",node=~\"$node\"}))*100"
    }
   ]
  },
  {
   "title": "Cluster CPU Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_num_cpu:sum{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_memory_MemAvailable_bytes{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\",node=~\"$node\",mountpoint=\"/\"})-sum(node_filesystem_avail_bytes{cluster=\"$cluster\",node=~\"$node\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\",node=~\"$node\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "expr": "sum (kubelet_running_pods{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pods Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kubelet_running_pods{cluster=\"$cluster\",node=~\"$node\"}) / sum (kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\",resource=\"pods\"})"
    }
   ]
  },
  {
   "title": "Available Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",node=~\"$node\",condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",node=~\"$node\",condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "(2m)Successful rate of Ingress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status!~\"^[4-5].*\", controller_class=~\"$controller_class\"}[$__interval])) / \r\n(sum(rate(nginx_ingress_controller_requests{ controller_class=~\"$controller_class\"}[$__interval])) - \r\n(sum(rate(nginx_ingress_controller_requests{status=~\"404|499\", controller_class=~\"$controller_class\"}[$__interval])) or vector(0)))"
    }
   ]
  },
  {
   "title": "Status of ingress controller",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_config_last_reload_successful{controller_class=~\"$controller_class\",container=\"controller\"}) by (controller_class)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Rate of CPU requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Rate of memory requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\"})/sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Active Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{cluster=\"$cluster\", phase=\"Active\"})"
    }
   ]
  },
  {
   "title": "Terminating of Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Terminating\"})"
    }
   ]
  },
  {
   "title": "Reboot required name",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kured_reboot_required{cluster=~\"$cluster\",node=~\"$node\"}) by (node) "
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace, pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace, pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace, pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace, pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace, pod)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace, pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace, pod)"
    },
    {
     "expr": "sum by(namespace, pod) (cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\", node=~\"$node\"})"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\",node=~\"$node\"}) by (namespace, pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", node=~\"$node\"}) by (namespace, pod)"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\",node=~\"$node\"}) by (node)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\",node=~\"$node\"}) by (node)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Namespace Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace)"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\", node=~\"$node\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", instance=~\"$node\"}) by (namespace) / sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\",node=~\"$node\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (namespace)"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}